// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXPdy5HmKT4M_JwpEpipsJcpjsB3Kv0Y',
    appId: '1:1066987203735:web:e027e6b7a7ec199e1c0dd2',
    messagingSenderId: '1066987203735',
    projectId: 'xdnotes-flutter-project',
    authDomain: 'xdnotes-flutter-project.firebaseapp.com',
    storageBucket: 'xdnotes-flutter-project.appspot.com',
    measurementId: 'G-RX1T3EQ55B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2N3cco1z95vanp_1u_lM-DHehdEpdbo',
    appId: '1:1066987203735:android:a4cec0899d53cc3c1c0dd2',
    messagingSenderId: '1066987203735',
    projectId: 'xdnotes-flutter-project',
    storageBucket: 'xdnotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqtYwEgLM1WnURul90W7URiT2tUz9OeA',
    appId: '1:1066987203735:ios:33f07c2e8aa136841c0dd2',
    messagingSenderId: '1066987203735',
    projectId: 'xdnotes-flutter-project',
    storageBucket: 'xdnotes-flutter-project.appspot.com',
    iosClientId: '1066987203735-offgu317kl1baubnsld751m4g1sogt5q.apps.googleusercontent.com',
    iosBundleId: 'com.diamonx.xdnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLqtYwEgLM1WnURul90W7URiT2tUz9OeA',
    appId: '1:1066987203735:ios:33f07c2e8aa136841c0dd2',
    messagingSenderId: '1066987203735',
    projectId: 'xdnotes-flutter-project',
    storageBucket: 'xdnotes-flutter-project.appspot.com',
    iosClientId: '1066987203735-offgu317kl1baubnsld751m4g1sogt5q.apps.googleusercontent.com',
    iosBundleId: 'com.diamonx.xdnotes',
  );
}
